### ISSUE TITLE
Demo can not be installed

### ISSUE THREAD

**Issue by mectors** [qor/qor-example#27]
I tried: go get -u github.com/qor/qor-example but there is a bunch of gorm and gopkg errors.

**Comment by pfzero** [comment]
Same happens to me as well...

$ go get -u github.com/qor/qor-example
# cd D:\work\golang\src\golang.org\x\image; hg pull
abort: HTTP Error 404: Not Found
package golang.org/x/image/bmp: exit status 255

**Comment by alexmironof** [comment]
@mectors @pfzero Can u check it? I think it is fixed now

**Comment by jinzhu** [comment]
going to close this one first, let me know if still have problems.
